migrate_plus.source.dcat.*:
  type: migrate_source
  label: 'DCAT feed'
  mapping:
    format:
      type: string
      label: 'Format'
    uri:
      type: uri
      label: 'URI'
    lowercase_taxonomy_terms:
      type: boolean
      label: 'Lowercase taxonomy terms'
    import_langcode:
      type: string
      label: 'Import language'
    track_changes:
      type: boolean
      lable: 'Track changes'
