dcat_import.settings:
  type: config_object
  label: 'DCAT import settings'
  mapping:
    global_theme:
      type: mapping
      label: 'Global theme'
      mapping:
        iri:
          type: uri
          label: 'Global theme iri'
        format:
          type: string
          label: 'Global theme format'
