dcat_export.settings:
  type: config_object
  label: General settings
  mapping:
    sources:
      type: sequence
      label: The sources to include in the export feed.
      sequence:
        type: string
    formats:
      type: sequence
      label: The supported export formats.
      sequence:
        type: string
    catalog_title:
      type: label
      label: The title of the DCAT feed.
      translatable: true
    catalog_description:
      type: text
      label: The description of the DCAT feed.
      translatable: true
    catalog_uri:
      type: label
      label: The URI of the catalog.
      translatable: true
    catalog_language_uri:
      type: label
      label: The URI of the catalog language.
      translatable: true
    catalog_homepage_uri:
      type: label
      label: The homepage of the DCAT feed.
      translatable: true
    catalog_issued:
      type: label
      label: The date when this feed was first issued.
    catalog_publisher_uri:
      type: label
      label: The uri of the publisher of this feed.
      translatable: true
    catalog_publisher_name:
      type: label
      label: The name of the publisher of this feed.
      translatable: true
    catalog_license_uri:
      type: label
      label: The license document under which the catalog is made available.
      translatable: true
